#!/bin/bash

# This script generates and submits a SLURM job for the LightGBM Classification pipeline.
# Outputs are organized into unique, job-specific directories and named according to submission guidelines.
# Personal information (First Name, Last Name, Email) is sourced from an external 'email.conf' file.

# --- Configuration for this SLURM Submission Script ---

# 1. Define the name for the temporary SLURM script file
TMP_SLURM_SCRIPT_NAME="lgbm_classification_job_submit.slurm"

# 2. Define shell variables for SLURM resource requests
REQUESTED_MEM="32G"         # Memory request
REQUESTED_CPUS="16"         # Total CPUs. Python script's --optuna_n_jobs and LGBM's internal n_jobs will use these.
REQUESTED_TIME="08:00:00"   # Requested wall time
JOB_NAME_BASE="LGBM_Cls_Pipeline" # Job name base for this classification task

# --- Personal Information and Email Configuration ---
YOUR_EMAIL=""
SUBMISSION_FIRST_NAME=""
SUBMISSION_LAST_NAME=""

# 3. Source personal information from email.conf
CONF_FILE="email.conf"
echo "Looking for personal information configuration in: $(pwd)/${CONF_FILE}"
if [[ -f "$CONF_FILE" ]]; then
    source "$CONF_FILE"
    echo "Sourced personal info from $CONF_FILE:"
    if [[ -n "$YOUR_EMAIL" ]]; then echo "  Email: $YOUR_EMAIL"; else echo "  Warning: YOUR_EMAIL not set in $CONF_FILE."; YOUR_EMAIL=""; fi
    if [[ -n "$SUBMISSION_FIRST_NAME" ]]; then echo "  First Name: $SUBMISSION_FIRST_NAME"; else echo "  Warning: SUBMISSION_FIRST_NAME not set in $CONF_FILE."; SUBMISSION_FIRST_NAME="FirstNameMissing"; fi
    if [[ -n "$SUBMISSION_LAST_NAME" ]]; then echo "  Last Name: $SUBMISSION_LAST_NAME"; else echo "  Warning: SUBMISSION_LAST_NAME not set in $CONF_FILE."; SUBMISSION_LAST_NAME="LastNameMissing"; fi
else
    echo "Warning: Configuration file '$CONF_FILE' not found in $(pwd)."
    YOUR_EMAIL=""; SUBMISSION_FIRST_NAME="FirstNameNotFound"; SUBMISSION_LAST_NAME="LastNameNotFound"
fi

# 4. Define the absolute path to your project's root directory
PROJECT_ROOT="/groups/kemi/kqd720/AppML/AppliedML2025/InitialProject" # MODIFY AS NEEDED

# 5. Define the name of your Python classification pipeline script
PYTHON_PIPELINE_SCRIPT="run_classification_pipeline.py" # THIS MUST MATCH YOUR SCRIPT NAME

# --- Submission Naming Parameters (Solution Name is set here) ---
SUBMISSION_SOLUTION_NAME="LGBM_Optuna_Run1" # MODIFY with a descriptive solution name

# 6. Define parameters to be passed to the Python script
PYTHON_TRAIN_PATH="./data/AppML_InitialProject_train.h5"
PYTHON_TEST_PATH_CLS="./data/AppML_InitialProject_test_classification.h5"
PYTHON_TARGET_COLUMN_CLS="p_Truth_isElectron"
PYTHON_EXCLUDE_COLUMNS_CLS="p_Truth_Energy"
PYTHON_RANDOM_SEED=42
PYTHON_VALIDATION_SIZE=0.20
PYTHON_DEV_TEST_SIZE=0.15
PYTHON_CV_FOLDS=5
PYTHON_MAX_FEATURES_ANALYSIS=25
PYTHON_ACCEPTABLE_ROC_AUC=0.98
PYTHON_OUTER_LOOP_PATIENCE=3
PYTHON_MIN_ROC_AUC_IMPROVEMENT=0.0005
PYTHON_N_OPTUNA_TRIALS=50
PYTHON_OPTUNA_N_JOBS=4

# --- Flags for the Python script ---
PYTHON_USE_PREDEFINED_PARAMS_FLAG=""
PYTHON_SAVE_CHECKPOINT_S5_5_FLAG="--save_checkpoint_s5_5"
PYTHON_LOAD_CHECKPOINT_S6_FLAG=""
PYTHON_LOAD_CHECKPOINT_S7_FLAG=""
PYTHON_SKIP_VIS_S2_5_FLAG=""
PYTHON_SKIP_SHAP_S3_5_FLAG=""


# --- Create the SLURM script content using a "here document" ---
echo "Generating SLURM script content for LightGBM Classification Pipeline in $TMP_SLURM_SCRIPT_NAME..."
cat > "$TMP_SLURM_SCRIPT_NAME" <<EOF
#!/bin/bash
# SLURM script generated by: $0 on \$(date) for LightGBM Classification task

#----------------------------------------------------------------#
# SLURM Directives                                               #
#----------------------------------------------------------------#
#SBATCH --job-name=${JOB_NAME_BASE}_${SUBMISSION_SOLUTION_NAME}_%j # Use %j for SLURM Job ID
#SBATCH --account=chemistry # MODIFY if needed
# Use %j for SLURM to expand to Job ID for output paths. SLURM will create the job_%j directory.
# CORRECTED: Changed base path to job_runs_classification
# CORRECTED: Simplified path using %j directly for the job ID folder
#SBATCH --output=${PROJECT_ROOT}/job_runs_classification/job_%j/slurm_output-%j.out
#SBATCH --error=${PROJECT_ROOT}/job_runs_classification/job_%j/slurm_error-%j.err
#SBATCH --partition=kemi6 # MODIFY if needed
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=${REQUESTED_CPUS}
#SBATCH --mem=${REQUESTED_MEM}
#SBATCH --time=${REQUESTED_TIME}
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=${YOUR_EMAIL}

#----------------------------------------------------------------#
# Environment Setup and Script Execution                         #
#----------------------------------------------------------------#
echo "--------------------------------------------------------"
echo "SLURM Job ID: \$SLURM_JOB_ID" # This variable is set by SLURM in the job's environment
echo "SLURM CPUs per task: \$SLURM_CPUS_PER_TASK"
echo "Project Root: ${PROJECT_ROOT}"
echo "Python script: ${PYTHON_PIPELINE_SCRIPT}"
echo "Submission Details: Classification_${SUBMISSION_FIRST_NAME}${SUBMISSION_LAST_NAME}_${SUBMISSION_SOLUTION_NAME}"
echo "Hostname: \$(hostname)"
echo "Working directory: \$(pwd)"
echo "Starting time: \$(date)"
echo "--------------------------------------------------------"

echo "Changing working directory to PROJECT_ROOT: ${PROJECT_ROOT}"
cd "${PROJECT_ROOT}"
if [ \$? -ne 0 ]; then echo "ERROR: cd to PROJECT_ROOT failed"; exit 1; fi
echo "Current Working Directory: \$(pwd)"

# Define the base directory for this job's Python outputs using the SLURM_JOB_ID environment variable
# CORRECTED: Changed base path to job_runs_classification
# This directory (job_runs_classification/job_SLURM_JOB_ID) should be created by SLURM due to --output directive.
# We will create a subdirectory within it for Python outputs.
JOB_BASE_DIR_FOR_SLURM_JOB="${PROJECT_ROOT}/job_runs_classification/job_\$SLURM_JOB_ID"
JOB_PYTHON_OUTPUT_DIR="\${JOB_BASE_DIR_FOR_SLURM_JOB}/python_outputs_${SUBMISSION_SOLUTION_NAME}"

# Ensure the base directory for this job exists (SLURM should create it for --output, but -p helps ensure it)
mkdir -p "\$JOB_BASE_DIR_FOR_SLURM_JOB"
if [ \$? -ne 0 ]; then echo "ERROR: mkdir for job base directory failed: \$JOB_BASE_DIR_FOR_SLURM_JOB"; exit 1; fi

# Then create the specific Python output subdirectory
mkdir -p "\$JOB_PYTHON_OUTPUT_DIR"
if [ \$? -ne 0 ]; then echo "ERROR: mkdir for Python output directory failed: \$JOB_PYTHON_OUTPUT_DIR"; exit 1; fi

echo "Python outputs (including submission CSVs) will be in: \$JOB_PYTHON_OUTPUT_DIR"

# 1. Initialize Micromamba
echo "--- Setting up Micromamba Environment ---"
export MAMBA_EXE='${MAMBA_EXE:-/lustre/hpc/kemi/kqd720/opt/x/micromamba}'
export MAMBA_ROOT_PREFIX='${MAMBA_ROOT_PREFIX:-/lustre/hpc/kemi/kqd720/micromamba}'
if [ ! -x "\$MAMBA_EXE" ]; then echo "ERROR: Micromamba not found at \$MAMBA_EXE"; exit 1; fi

__mamba_setup="\$("\$MAMBA_EXE" shell hook --shell bash --root-prefix "\$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ \$? -eq 0 ] && [ -n "\$__mamba_setup" ]; then
    eval "\$__mamba_setup";
else
    if [ -f "\$MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh" ]; then
        source "\$MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh"
    else
        echo "ERROR: Micromamba init failed." ; exit 1;
    fi
fi
unset __mamba_setup; echo "Micromamba hook initialized."

# 2. Activate Micromamba environment
ENV_NAME="${ENV_NAME:-AppML}"
echo "Activating Micromamba environment: \$ENV_NAME"
micromamba activate \$ENV_NAME
if [ \$? -ne 0 ]; then echo "ERROR: Failed to activate env '\$ENV_NAME'."; exit 1; fi
echo "Python: \$(which python), Version: \$(python --version)"
echo "LightGBM: \$(python -c 'import lightgbm; print(lightgbm.__version__)' 2>/dev/null || echo 'Not found')"
echo "SHAP: \$(python -c 'import shap; print(shap.__version__)' 2>/dev/null || echo 'Not found')"
echo "Optuna: \$(python -c 'import optuna; print(optuna.__version__)' 2>/dev/null || echo 'Not found')"
echo "Scikit-learn: \$(python -c 'import sklearn; print(sklearn.__version__)' 2>/dev/null || echo 'Not found')"
echo "------------------------------------------"

# 3. Construct and Execute Python script command
PYTHON_SCRIPT_TO_RUN="${PYTHON_PIPELINE_SCRIPT}"

PYTHON_CMD="python -u ./\$PYTHON_SCRIPT_TO_RUN"
PYTHON_CMD+=" --output_base_dir \"\$JOB_PYTHON_OUTPUT_DIR\""
PYTHON_CMD+=" --firstname \"${SUBMISSION_FIRST_NAME}\""
PYTHON_CMD+=" --lastname \"${SUBMISSION_LAST_NAME}\""
PYTHON_CMD+=" --solution_name \"${SUBMISSION_SOLUTION_NAME}\""
PYTHON_CMD+=" --train_path \"${PYTHON_TRAIN_PATH}\""
PYTHON_CMD+=" --test_path \"${PYTHON_TEST_PATH_CLS}\""
PYTHON_CMD+=" --target_column \"${PYTHON_TARGET_COLUMN_CLS}\""
if [ -n "${PYTHON_EXCLUDE_COLUMNS_CLS}" ]; then PYTHON_CMD+=" --exclude_columns ${PYTHON_EXCLUDE_COLUMNS_CLS}"; fi
PYTHON_CMD+=" --random_seed ${PYTHON_RANDOM_SEED}"
PYTHON_CMD+=" --validation_size ${PYTHON_VALIDATION_SIZE}"
PYTHON_CMD+=" --dev_test_size ${PYTHON_DEV_TEST_SIZE}"
PYTHON_CMD+=" --cv_folds ${PYTHON_CV_FOLDS}"
PYTHON_CMD+=" --max_features_analysis ${PYTHON_MAX_FEATURES_ANALYSIS}"
PYTHON_CMD+=" --acceptable_roc_auc ${PYTHON_ACCEPTABLE_ROC_AUC}"
PYTHON_CMD+=" --outer_loop_patience ${PYTHON_OUTER_LOOP_PATIENCE}"
PYTHON_CMD+=" --min_roc_auc_improvement ${PYTHON_MIN_ROC_AUC_IMPROVEMENT}"
PYTHON_CMD+=" --n_optuna_trials ${PYTHON_N_OPTUNA_TRIALS}"
PYTHON_CMD+=" --optuna_n_jobs ${PYTHON_OPTUNA_N_JOBS}"

if [ -n "${PYTHON_USE_PREDEFINED_PARAMS_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_USE_PREDEFINED_PARAMS_FLAG}"; fi
if [ -n "${PYTHON_SAVE_CHECKPOINT_S5_5_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SAVE_CHECKPOINT_S5_5_FLAG}"; fi
if [ -n "${PYTHON_LOAD_CHECKPOINT_S6_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_LOAD_CHECKPOINT_S6_FLAG}"; fi
if [ -n "${PYTHON_LOAD_CHECKPOINT_S7_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_LOAD_CHECKPOINT_S7_FLAG}"; fi
if [ -n "${PYTHON_SKIP_VIS_S2_5_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SKIP_VIS_S2_5_FLAG}"; fi
if [ -n "${PYTHON_SKIP_SHAP_S3_5_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SKIP_SHAP_S3_5_FLAG}"; fi

echo ""
echo "--- Running Python LightGBM Classification Pipeline Script ---"
printf "Executing Python Command:\n%s\n" "\$PYTHON_CMD"
echo "--------------------------------------------------------"
eval "\$PYTHON_CMD"

SCRIPT_EXIT_STATUS=\$?
if [ \$SCRIPT_EXIT_STATUS -eq 0 ]; then
    echo "Python script '\$PYTHON_SCRIPT_TO_RUN' completed successfully."
    echo "Submission files (e.g., Classification_${SUBMISSION_FIRST_NAME}${SUBMISSION_LAST_NAME}_${SUBMISSION_SOLUTION_NAME}.csv) should be in \$JOB_PYTHON_OUTPUT_DIR"
else
    echo "ERROR: Python script '\$PYTHON_SCRIPT_TO_RUN' exited with status \$SCRIPT_EXIT_STATUS."
fi
echo "--------------------------------------------------------"

echo ""; echo "--- Cleaning Up ---"; echo "Deactivating Micromamba environment."
micromamba deactivate; echo "Micromamba environment deactivated."
echo "-------------------"

echo ""; echo "--------------------------------------------------------"
echo "Ending time: \$(date)"; echo "SLURM job finished."
echo "--------------------------------------------------------"
exit \$SCRIPT_EXIT_STATUS
EOF

if [ $? -eq 0 ]; then
    echo "Successfully wrote SLURM script content to $TMP_SLURM_SCRIPT_NAME"
else
    echo "ERROR writing to $TMP_SLURM_SCRIPT_NAME"; exit 1;
fi

echo ""; echo "Submitting generated SLURM script: $TMP_SLURM_SCRIPT_NAME to the queue..."

SBATCH_FULL_OUTPUT=$(sbatch "$TMP_SLURM_SCRIPT_NAME" 2>&1)
SBATCH_COMMAND_EXIT_CODE=$?

echo "Full output from sbatch command:"
echo "$SBATCH_FULL_OUTPUT"
echo "sbatch command finished with exit code: $SBATCH_COMMAND_EXIT_CODE"

SUBMITTED_JOB_ID=$(echo "$SBATCH_FULL_OUTPUT" | grep -oP 'Submitted batch job \K[0-9]+')

if [ -n "$SUBMITTED_JOB_ID" ]; then
    echo "Successfully submitted SLURM job. Job ID: $SUBMITTED_JOB_ID"
    if [ "$SBATCH_COMMAND_EXIT_CODE" -ne 0 ]; then
        echo "Warning: sbatch command exited non-zero (\$SBATCH_COMMAND_EXIT_CODE), but Job ID (\$SUBMITTED_JOB_ID) was parsed."
    fi
elif [ "$SBATCH_COMMAND_EXIT_CODE" -eq 0 ]; then
    echo "Warning: sbatch command exited successfully, but no Job ID was parsed."
else
    echo "ERROR: SLURM job submission failed. Exit code \$SBATCH_COMMAND_EXIT_CODE."
fi

echo ""; echo "LightGBM Classification Pipeline job submission process complete."

