#!/bin/bash

# This script generates and submits a SLURM job for the REGRESSION pipeline.
# Each job will have its outputs (SLURM logs and Python pipeline outputs)
# organized into a unique, job-specific directory.
# Personal information (First Name, Last Name, Email) is sourced from an external 'email.conf' file.

# --- Configuration for this SLURM Submission Script ---

# 1. Define the name for the temporary SLURM script file that will be generated
TMP_SLURM_SCRIPT_NAME="my_lgbm_regression_job_submit.slurm"

# 2. Define shell variables for SLURM resource requests
REQUESTED_MEM="32G"
REQUESTED_CPUS="8"    # Adjust if your Python script uses more for Optuna/LGBM
REQUESTED_TIME="04:00:00" # Adjust based on expected runtime of regression pipeline
JOB_NAME_BASE="LGBM_Regression"

# --- Personal Information and Email Configuration ---
# These will be sourced from 'email.conf'
YOUR_EMAIL=""
SUBMISSION_FIRST_NAME=""
SUBMISSION_LAST_NAME=""

# 3. Source personal information from email.conf
# The email.conf file should contain lines like:
# YOUR_EMAIL="your.email@example.com"
# SUBMISSION_FIRST_NAME="YourFirstName"
# SUBMISSION_LAST_NAME="YourLastName"
CONF_FILE="email.conf"
echo "Looking for personal information configuration in: $(pwd)/${CONF_FILE}"
if [[ -f "$CONF_FILE" ]]; then
    source "$CONF_FILE" # Source the file to load the variables
    echo "Sourced personal info from $CONF_FILE:"
    if [[ -n "$YOUR_EMAIL" ]]; then
        echo "  Email: $YOUR_EMAIL"
    else
        echo "  Warning: YOUR_EMAIL not set or empty in $CONF_FILE. Email notifications may be affected."
        YOUR_EMAIL="" # Ensure it's empty if not properly set
    fi
    if [[ -n "$SUBMISSION_FIRST_NAME" ]]; then
        echo "  First Name: $SUBMISSION_FIRST_NAME"
    else
        echo "  Warning: SUBMISSION_FIRST_NAME not set or empty in $CONF_FILE. Output file naming will be affected."
        SUBMISSION_FIRST_NAME="FirstNameMissing" # Default placeholder
    fi
    if [[ -n "$SUBMISSION_LAST_NAME" ]]; then
        echo "  Last Name: $SUBMISSION_LAST_NAME"
    else
        echo "  Warning: SUBMISSION_LAST_NAME not set or empty in $CONF_FILE. Output file naming will be affected."
        SUBMISSION_LAST_NAME="LastNameMissing" # Default placeholder
    fi
else
    echo "Warning: Configuration file '$CONF_FILE' not found in $(pwd)."
    echo "  Email notifications will likely be disabled, and output file naming will use placeholders."
    YOUR_EMAIL=""
    SUBMISSION_FIRST_NAME="FirstNameNotFound"
    SUBMISSION_LAST_NAME="LastNameNotFound"
fi

# 4. Define the absolute path to your project's root directory
PROJECT_ROOT="/groups/kemi/kqd720/AppML/AppliedML2025/InitialProject" # MODIFY AS NEEDED

# 5. Define the name of your Python pipeline script for REGRESSION
PYTHON_REGRESSION_SCRIPT="run_regression_pipeline.py" # This is your target Python script

# --- Submission Naming Parameters (Solution Name is set here) ---
# First Name and Last Name are sourced from email.conf
# MODIFY this solution name as needed for different regression runs/models
SUBMISSION_SOLUTION_NAME_REG="LGBM_Reg_Run1"

# 6. Define parameters to be passed to the Python regression script
#    These correspond to the argparse arguments in 'run_regression_pipeline.py'.
#    Modify these values as needed for different regression runs.

# Data and Core Config
PYTHON_TRAIN_PATH_REG="./data/AppML_InitialProject_train.h5"
PYTHON_TEST_PATH_REG="./data/AppML_InitialProject_test_regression.h5"
PYTHON_ELECTRON_FLAG_COLUMN_REG="p_Truth_isElectron"
PYTHON_TARGET_COLUMN_REG="p_Truth_Energy"
PYTHON_EXCLUDE_COLUMNS_REG_ARR=("p_Truth_isElectron" "p_Truth_Energy") # Bash array
PYTHON_RANDOM_SEED_REG=42
PYTHON_VALIDATION_SIZE_REG=0.20
PYTHON_DEV_TEST_SIZE_REG=0.15

# Feature Analysis and Selection Config (Regression)
PYTHON_CV_FOLDS_REG=5
PYTHON_MAX_FEATURES_ANALYSIS_REG=15
PYTHON_ACCEPTABLE_REL_MAE_REG=0.1
PYTHON_OUTER_LOOP_PATIENCE_REG=3
PYTHON_MIN_REL_MAE_IMPROVEMENT_REG=0.001

# Optuna Config (Regression)
PYTHON_N_OPTUNA_TRIALS_REG=50
PYTHON_OPTUNA_N_JOBS_REG=1 # Default for Optuna parallelism in Python script

# Python script toggles for regression (action='store_true' flags)
PYTHON_USE_PREDEFINED_PARAMS_REG_FLAG=""
PYTHON_SAVE_CHECKPOINT_REG_S5_5_FLAG=""
PYTHON_LOAD_CHECKPOINT_REG_S6_FLAG=""
PYTHON_LOAD_CHECKPOINT_REG_S7_FLAG=""
PYTHON_SKIP_VIS_REG_S2_5_FLAG=""
PYTHON_SKIP_SHAP_REG_S3_5_FLAG=""


# --- Create the SLURM script content using a "here document" ---
echo "Generating SLURM script content for REGRESSION in $TMP_SLURM_SCRIPT_NAME..."
cat > "$TMP_SLURM_SCRIPT_NAME" <<EOF
#!/bin/bash
# SLURM script generated by: $0 on \$(date) for REGRESSION task

#----------------------------------------------------------------#
# SLURM Directives                                               #
#----------------------------------------------------------------#
#SBATCH --job-name=${JOB_NAME_BASE}_${SUBMISSION_SOLUTION_NAME_REG}_%j # Include solution name and job ID
#SBATCH --account=chemistry # MODIFY if needed
#SBATCH --output=${PROJECT_ROOT}/job_runs_regression/job_%j/slurm_regression-%j.out
#SBATCH --error=${PROJECT_ROOT}/job_runs_regression/job_%j/slurm_regression-%j.err
#SBATCH --partition=kemi6 # MODIFY if needed
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=${REQUESTED_CPUS}
#SBATCH --mem=${REQUESTED_MEM}
#SBATCH --time=${REQUESTED_TIME}
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=${YOUR_EMAIL} # Sourced by generator script

#----------------------------------------------------------------#
# Environment Setup and Script Execution                         #
#----------------------------------------------------------------#
echo "--------------------------------------------------------"
echo "SLURM Job ID: \$SLURM_JOB_ID"
echo "SLURM Job Name: \$SLURM_JOB_NAME"
echo "Running on host: \$(hostname)"
echo "Project Root Directory: ${PROJECT_ROOT}"
echo "Python script to run: ${PYTHON_REGRESSION_SCRIPT}"
echo "Submission First Name: ${SUBMISSION_FIRST_NAME}" # Sourced by generator
echo "Submission Last Name: ${SUBMISSION_LAST_NAME}"   # Sourced by generator
echo "Submission Solution Name: ${SUBMISSION_SOLUTION_NAME_REG}" # From generator
echo "Working Directory will be changed to: ${PROJECT_ROOT}"
echo "Account: \$(scontrol show job \$SLURM_JOBID | grep -oP 'Account=\K[^ ]+')"
echo "Partition: \$(scontrol show job \$SLURM_JOBID | grep -oP 'Partition=\K[^ ]+')"
echo "Requested CPUs: ${REQUESTED_CPUS}, Memory: ${REQUESTED_MEM}"
echo "Email notifications will be sent to: ${YOUR_EMAIL:-'Not Set (email.conf missing or YOUR_EMAIL empty)'}"
echo "Starting time: \$(date)"
echo "--------------------------------------------------------"

echo "Changing working directory to PROJECT_ROOT: ${PROJECT_ROOT}"
cd "${PROJECT_ROOT}"
if [ \$? -ne 0 ]; then echo "ERROR: Failed to change directory to PROJECT_ROOT: ${PROJECT_ROOT}"; exit 1; fi
echo "Current Working Directory: \$(pwd)"

JOB_BASE_DIR_FOR_SLURM_JOB="${PROJECT_ROOT}/job_runs_regression/job_\$SLURM_JOB_ID"
JOB_PYTHON_OUTPUT_DIR_REG="\${JOB_BASE_DIR_FOR_SLURM_JOB}/python_outputs_${SUBMISSION_SOLUTION_NAME_REG}"

mkdir -p "\$JOB_BASE_DIR_FOR_SLURM_JOB" # SLURM should create job_%j, but -p is safe
if [ \$? -ne 0 ]; then echo "Warning: mkdir for job base directory \$JOB_BASE_DIR_FOR_SLURM_JOB might have failed (SLURM should create it)."; fi

mkdir -p "\$JOB_PYTHON_OUTPUT_DIR_REG"
if [ \$? -ne 0 ]; then echo "ERROR: mkdir for Python output directory failed: \$JOB_PYTHON_OUTPUT_DIR_REG"; exit 1; fi
echo "Python outputs will be in: \$JOB_PYTHON_OUTPUT_DIR_REG"

# 1. Initialize Micromamba
echo ""
echo "--- Setting up Micromamba Environment ---"
export MAMBA_EXE='${MAMBA_EXE:-/lustre/hpc/kemi/kqd720/opt/x/micromamba}'
export MAMBA_ROOT_PREFIX='${MAMBA_ROOT_PREFIX:-/lustre/hpc/kemi/kqd720/micromamba}'
if [ ! -x "\$MAMBA_EXE" ]; then echo "ERROR: Micromamba not found at \$MAMBA_EXE"; exit 1; fi
__mamba_setup="\$("\$MAMBA_EXE" shell hook --shell bash --root-prefix "\$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ \$? -eq 0 ] && [ -n "\$__mamba_setup" ]; then eval "\$__mamba_setup"; else echo "ERROR: Micromamba hook failed."; exit 1; fi
unset __mamba_setup; echo "Micromamba shell hook initialized successfully."

# 2. Activate Micromamba environment
ENV_NAME="${ENV_NAME:-AppML}" # Use ENV_NAME from generator or default
echo "Activating Micromamba environment: \$ENV_NAME"
micromamba activate \$ENV_NAME
if [ \$? -ne 0 ]; then echo "ERROR: Failed to activate environment '\$ENV_NAME'."; exit 1; fi
echo "Micromamba environment activated. Python: \$(which python)"
echo "LightGBM version: \$(python -c 'import lightgbm; print(lightgbm.__version__)' 2>/dev/null || echo 'Not found')"
echo "Optuna version: \$(python -c 'import optuna; print(optuna.__version__)' 2>/dev/null || echo 'Not found')"
echo "SHAP version: \$(python -c 'import shap; print(shap.__version__)' 2>/dev/null || echo 'Not found')"
echo "------------------------------------------"

# 3. Construct and Execute Python REGRESSION script command
PYTHON_SCRIPT_TO_RUN_REG="${PYTHON_REGRESSION_SCRIPT}"

PYTHON_CMD="python -u ./\$PYTHON_SCRIPT_TO_RUN_REG"
PYTHON_CMD+=" --output_base_dir \"\$JOB_PYTHON_OUTPUT_DIR_REG\""
# --- Add submission naming args (values from generator script) ---
PYTHON_CMD+=" --firstname \"${SUBMISSION_FIRST_NAME}\""
PYTHON_CMD+=" --lastname \"${SUBMISSION_LAST_NAME}\""
PYTHON_CMD+=" --solution_name \"${SUBMISSION_SOLUTION_NAME_REG}\"" # Use the regression-specific solution name
# --- End of submission naming args ---
PYTHON_CMD+=" --train_path \"${PYTHON_TRAIN_PATH_REG}\""
PYTHON_CMD+=" --test_path \"${PYTHON_TEST_PATH_REG}\""
PYTHON_CMD+=" --electron_flag_column \"${PYTHON_ELECTRON_FLAG_COLUMN_REG}\""
PYTHON_CMD+=" --target_column_reg \"${PYTHON_TARGET_COLUMN_REG}\""
exclude_opts_reg_str=""
for item_reg in "${PYTHON_EXCLUDE_COLUMNS_REG_ARR[@]}"; do
    exclude_opts_reg_str+=" \"\$item_reg\"" # Correctly quote each item
done
if [ -n "\$exclude_opts_reg_str" ]; then
    # Ensure the argument name is correctly spaced from its values
    PYTHON_CMD+=" --exclude_columns_reg\${exclude_opts_reg_str}"
fi
PYTHON_CMD+=" --random_seed ${PYTHON_RANDOM_SEED_REG}"
PYTHON_CMD+=" --validation_size_reg ${PYTHON_VALIDATION_SIZE_REG}"
PYTHON_CMD+=" --dev_test_size_reg ${PYTHON_DEV_TEST_SIZE_REG}"
PYTHON_CMD+=" --cv_folds_reg ${PYTHON_CV_FOLDS_REG}"
PYTHON_CMD+=" --max_features_analysis_reg ${PYTHON_MAX_FEATURES_ANALYSIS_REG}"
PYTHON_CMD+=" --acceptable_rel_mae ${PYTHON_ACCEPTABLE_REL_MAE_REG}"
PYTHON_CMD+=" --outer_loop_patience_reg ${PYTHON_OUTER_LOOP_PATIENCE_REG}"
PYTHON_CMD+=" --min_rel_mae_improvement ${PYTHON_MIN_REL_MAE_IMPROVEMENT_REG}"
PYTHON_CMD+=" --n_optuna_trials_reg ${PYTHON_N_OPTUNA_TRIALS_REG}"
PYTHON_CMD+=" --optuna_n_jobs_reg ${PYTHON_OPTUNA_N_JOBS_REG}"

if [ -n "${PYTHON_USE_PREDEFINED_PARAMS_REG_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_USE_PREDEFINED_PARAMS_REG_FLAG}"; fi
if [ -n "${PYTHON_SAVE_CHECKPOINT_REG_S5_5_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SAVE_CHECKPOINT_REG_S5_5_FLAG}"; fi
if [ -n "${PYTHON_LOAD_CHECKPOINT_REG_S6_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_LOAD_CHECKPOINT_REG_S6_FLAG}"; fi
if [ -n "${PYTHON_LOAD_CHECKPOINT_REG_S7_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_LOAD_CHECKPOINT_REG_S7_FLAG}"; fi
if [ -n "${PYTHON_SKIP_VIS_REG_S2_5_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SKIP_VIS_REG_S2_5_FLAG}"; fi
if [ -n "${PYTHON_SKIP_SHAP_REG_S3_5_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SKIP_SHAP_REG_S3_5_FLAG}"; fi

echo ""
echo "--- Running Python REGRESSION Script ---"
printf "Executing Python Command: %s\n" "\$PYTHON_CMD"
eval "\$PYTHON_CMD"

SCRIPT_EXIT_STATUS=\$?
if [ \$SCRIPT_EXIT_STATUS -eq 0 ]; then echo "Python script '\$PYTHON_SCRIPT_TO_RUN_REG' completed successfully."
else echo "ERROR: Python script '\$PYTHON_SCRIPT_TO_RUN_REG' exited with status \$SCRIPT_EXIT_STATUS."; fi
echo "---------------------------"

# 4. Deactivate Micromamba environment
echo ""; echo "--- Cleaning Up ---"; echo "Deactivating Micromamba environment."
micromamba deactivate; echo "-------------------"

echo ""; echo "--------------------------------------------------------"
echo "Ending time: \$(date)"; echo "SLURM job finished."
echo "--------------------------------------------------------"
exit \$SCRIPT_EXIT_STATUS
EOF

if [ $? -eq 0 ]; then
    echo "Successfully wrote SLURM script content for REGRESSION to $TMP_SLURM_SCRIPT_NAME"
else
    echo "ERROR: Failed to write SLURM script content for REGRESSION to $TMP_SLURM_SCRIPT_NAME"; exit 1
fi

# --- Submit the generated SLURM script ---
echo ""; echo "Submitting generated REGRESSION SLURM script: $TMP_SLURM_SCRIPT_NAME to the queue..."
SBATCH_FULL_OUTPUT=$(sbatch "$TMP_SLURM_SCRIPT_NAME" 2>&1)
SBATCH_COMMAND_EXIT_CODE=$?

echo "Full output from sbatch command:"
echo "$SBATCH_FULL_OUTPUT"
echo "sbatch command finished with exit code: $SBATCH_COMMAND_EXIT_CODE"

SUBMITTED_JOB_ID=$(echo "$SBATCH_FULL_OUTPUT" | grep -oP 'Submitted batch job \K[0-9]+')

if [ -n "$SUBMITTED_JOB_ID" ]; then
    echo "Successfully submitted SLURM job. Job ID: $SUBMITTED_JOB_ID"
    if [ "$SBATCH_COMMAND_EXIT_CODE" -ne 0 ]; then
        echo "Warning: The sbatch command exited with a non-zero status ($SBATCH_COMMAND_EXIT_CODE), but a Job ID ($SUBMITTED_JOB_ID) was parsed."
    fi
elif [ "$SBATCH_COMMAND_EXIT_CODE" -eq 0 ]; then
    echo "Warning: sbatch command exited successfully, but no Job ID was parsed."
else
    echo "ERROR: SLURM job submission failed. Exit code \$SBATCH_COMMAND_EXIT_CODE."
fi

echo ""; echo "Regression job submission process complete."

