#!/bin/bash

# This script generates and submits a SLURM job for the Unsupervised Clustering pipeline.
# All outputs for a given job (SLURM logs and Python script outputs) are organized
# into a unique, job-specific directory under JOB_OUTPUT_PARENT_DIR.

# --- Configuration for this SLURM Submission Script ---

# 1. Define the name for the temporary SLURM script file that will be generated
TMP_SLURM_SCRIPT_NAME="clustering_job_submit_temp.slurm"

# 2. Define shell variables for SLURM resource requests
REQUESTED_MEM="32G"
REQUESTED_CPUS="8"
REQUESTED_TIME="08:00:00"
JOB_NAME_BASE="ClusteringPipeline"

# 3. Email for notifications (optional)
YOUR_EMAIL=""
EMAIL_CONF_FILE="email.conf" # Expects: YOUR_EMAIL="your.email@example.com"
echo "Looking for email configuration in: $(pwd)/${EMAIL_CONF_FILE}"
if [[ -f "$EMAIL_CONF_FILE" ]]; then
    source "$EMAIL_CONF_FILE"; echo "Sourced email: $YOUR_EMAIL"
    [[ -z "$YOUR_EMAIL" ]] && echo "Warning: YOUR_EMAIL empty in $EMAIL_CONF_FILE." && YOUR_EMAIL=""
else
    echo "Warning: $EMAIL_CONF_FILE not found. Email notifications for SLURM job status may be disabled or use default."
fi

# 4. Define the ABSOLUTE path to your project's root directory
PROJECT_ROOT="/groups/kemi/kqd720/AppML/AppliedML2025/InitialProject"

# 5. Define the name of your Python clustering pipeline script
PYTHON_CLUSTERING_SCRIPT_NAME="run_clustering_pipeline.py" # Assumes it's in PROJECT_ROOT

# 6. Define the name of your Micromamba environment
MAMBA_ENV_NAME="AppML"

# 7. Define the parent directory for all job-related outputs.
#    Job-specific subdirectories (job_XXXXX) will be created inside this.
JOB_OUTPUT_PARENT_DIR="job_runs_clustering"

# 8. SLURM Account and Partition
SLURM_ACCOUNT="chemistry"
SLURM_PARTITION="kemi6"

# 9. Micromamba paths (Verify these for your cluster environment)
MAMBA_EXE_PATH='/lustre/hpc/kemi/kqd720/opt/x/micromamba'
MAMBA_ROOT_PREFIX_PATH='/lustre/hpc/kemi/kqd720/micromamba'

# --- Pre-submission checks ---
if [ ! -d "${PROJECT_ROOT}" ]; then
    echo "ERROR: PROJECT_ROOT directory does not exist: ${PROJECT_ROOT}"
    exit 1
fi
if [ ! -f "${PROJECT_ROOT}/${PYTHON_CLUSTERING_SCRIPT_NAME}" ]; then
    echo "ERROR: Python script not found: ${PROJECT_ROOT}/${PYTHON_CLUSTERING_SCRIPT_NAME}"
    exit 1
fi

# --- Create the SLURM script content using a "here document" ---
echo "Generating SLURM script content for Clustering Pipeline in $TMP_SLURM_SCRIPT_NAME..."

# Ensure the JOB_OUTPUT_PARENT_DIR exists within the project root
mkdir -p "${PROJECT_ROOT}/${JOB_OUTPUT_PARENT_DIR}"
if [ $? -ne 0 ]; then
    echo "ERROR: Failed to create base output directory: ${PROJECT_ROOT}/${JOB_OUTPUT_PARENT_DIR}"
    exit 1
fi

cat > "$TMP_SLURM_SCRIPT_NAME" <<EOF
#!/bin/bash
# SLURM script generated by: $0 on $(date) for Clustering Pipeline task

#----------------------------------------------------------------#
# SLURM Directives
#----------------------------------------------------------------#
#SBATCH --job-name=${JOB_NAME_BASE}_%j
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --output=${PROJECT_ROOT}/${JOB_OUTPUT_PARENT_DIR}/job_%j/slurm_clustering-%j.out
#SBATCH --error=${PROJECT_ROOT}/${JOB_OUTPUT_PARENT_DIR}/job_%j/slurm_clustering-%j.err
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=${REQUESTED_CPUS}
#SBATCH --mem=${REQUESTED_MEM}
#SBATCH --time=${REQUESTED_TIME}
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=${YOUR_EMAIL}

#----------------------------------------------------------------#
# Environment Setup and Script Execution
#----------------------------------------------------------------#
echo "--------------------------------------------------------"
echo "SLURM Job ID: \$SLURM_JOB_ID"
echo "SLURM CPUs per task: \$SLURM_CPUS_PER_TASK"
echo "Requested Memory: ${REQUESTED_MEM}"
echo "Project Root Directory: ${PROJECT_ROOT}"
echo "Python script to run: ${PYTHON_CLUSTERING_SCRIPT_NAME}"
echo "Mamba environment: ${MAMBA_ENV_NAME}"
echo "Hostname: \$(hostname)"
echo "Submission directory: \$(pwd)" 
echo "Starting time: \$(date)"
echo "--------------------------------------------------------"

echo "Changing working directory to PROJECT_ROOT: ${PROJECT_ROOT}"
cd "${PROJECT_ROOT}"
if [ \$? -ne 0 ]; then echo "ERROR: cd to PROJECT_ROOT failed"; exit 1; fi
echo "Current Working Directory: \$(pwd)"
echo "--------------------------------------------------------"
echo "Contents of my_config.py (if it exists in PROJECT_ROOT):"
if [ -f "my_config.py" ]; then
    cat my_config.py
else
    echo "my_config.py not found in ${PROJECT_ROOT}"
fi
echo "--------------------------------------------------------"

JOB_SPECIFIC_DIR="${PROJECT_ROOT}/${JOB_OUTPUT_PARENT_DIR}/job_\$SLURM_JOB_ID"
echo "All outputs for this job (SLURM logs and Python files) will be in: \$JOB_SPECIFIC_DIR"

# 1. Initialize Micromamba
echo "--- Setting up Micromamba Environment ---"
export MAMBA_EXE='${MAMBA_EXE_PATH}'
export MAMBA_ROOT_PREFIX='${MAMBA_ROOT_PREFIX_PATH}'

if [ ! -x "\$MAMBA_EXE" ]; then echo "ERROR: Micromamba executable not found at \$MAMBA_EXE"; exit 1; fi

__mamba_setup="\$("\$MAMBA_EXE" shell hook --shell bash --root-prefix "\$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ \$? -eq 0 ] && [ -n "\$__mamba_setup" ]; then
    eval "\$__mamba_setup";
else
    echo "ERROR: Micromamba hook failed. Attempting to source profile.d script if it exists..."
    if [ -f "\$MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh" ]; then
        source "\$MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh"
    else
        echo "ERROR: Micromamba hook and profile.d script failed. Cannot initialize Micromamba."
        exit 1;
    fi
fi
unset __mamba_setup; echo "Micromamba hook initialized."

# 2. Activate Micromamba environment
echo "Activating Micromamba environment: ${MAMBA_ENV_NAME}"
micromamba activate "${MAMBA_ENV_NAME}"
if [ \$? -ne 0 ]; then echo "ERROR: Failed to activate env '${MAMBA_ENV_NAME}'. Ensure it exists."; exit 1; fi
echo "Micromamba environment activated."
echo "Python executable: \$(which python)"
echo "Python version: \$(python --version)"
echo "------------------------------------------"

# 3. Execute Python Clustering script
PYTHON_SCRIPT_PATH="./${PYTHON_CLUSTERING_SCRIPT_NAME}"
PYTHON_CMD="python -u \"\$PYTHON_SCRIPT_PATH\" --output_dir \"\$JOB_SPECIFIC_DIR\""

echo ""
echo "--- Running Python Clustering Pipeline Script ---"
printf "Executing Python Command:\n%s\n" "\$PYTHON_CMD"
echo "--------------------------------------------------------"

eval "\$PYTHON_CMD" 

SCRIPT_EXIT_STATUS=\$?
if [ \$SCRIPT_EXIT_STATUS -eq 0 ]; then
    echo "Python script '\$PYTHON_SCRIPT_PATH' completed successfully."
else
    echo "ERROR: Python script '\$PYTHON_SCRIPT_PATH' exited with status \$SCRIPT_EXIT_STATUS."
fi
echo "--------------------------------------------------------"

# 4. Deactivate Micromamba environment
echo ""; echo "--- Cleaning Up ---"; echo "Deactivating Micromamba environment."
micromamba deactivate; echo "Micromamba environment deactivated."
echo "-------------------"

echo ""; echo "--------------------------------------------------------"
echo "Ending time: \$(date)"; echo "SLURM job finished."
echo "--------------------------------------------------------"
exit \$SCRIPT_EXIT_STATUS
EOF

if [ $? -eq 0 ]; then
    echo "Successfully wrote SLURM script content for Clustering Pipeline to $TMP_SLURM_SCRIPT_NAME"
else
    echo "ERROR writing to $TMP_SLURM_SCRIPT_NAME"; exit 1;
fi

echo ""; echo "Submitting generated Clustering SLURM script: $TMP_SLURM_SCRIPT_NAME to the queue..."

# --- Submit the generated SLURM script ---
# Corrected line: Removed unnecessary backslash before $ for command substitution
SBATCH_FULL_OUTPUT=$(sbatch "$TMP_SLURM_SCRIPT_NAME" 2>&1)
SBATCH_COMMAND_EXIT_CODE=$?

echo "Full output from sbatch command:"
echo "$SBATCH_FULL_OUTPUT"
echo "sbatch command finished with exit code: $SBATCH_COMMAND_EXIT_CODE"

SUBMITTED_JOB_ID=$(echo "$SBATCH_FULL_OUTPUT" | grep -oP 'Submitted batch job \K[0-9]+')

if [ -n "$SUBMITTED_JOB_ID" ]; then
    echo "Successfully submitted SLURM job. Job ID: $SUBMITTED_JOB_ID"
    echo "All outputs for this job (SLURM logs and Python files) will be in: ${PROJECT_ROOT}/${JOB_OUTPUT_PARENT_DIR}/job_${SUBMITTED_JOB_ID}/"
    if [ "$SBATCH_COMMAND_EXIT_CODE" -ne 0 ]; then
        echo "Warning: The sbatch command exited with a non-zero status ($SBATCH_COMMAND_EXIT_CODE), but a Job ID ($SUBMITTED_JOB_ID) was parsed."
        echo "The job may have been submitted despite the warning. Please verify its status in the SLURM queue."
    fi
elif [ "$SBATCH_COMMAND_EXIT_CODE" -eq 0 ]; then
    echo "Warning: sbatch command exited successfully (code 0), but no Job ID could be parsed from its output."
    echo "Full sbatch output was: $SBATCH_FULL_OUTPUT"
    echo "Please check the SLURM queue manually to see if the job was submitted."
else
    echo "ERROR: SLURM job submission failed. sbatch command exited with status $SBATCH_COMMAND_EXIT_CODE and no Job ID was parsed."
    echo "Full sbatch output was: $SBATCH_FULL_OUTPUT"
fi

echo ""; echo "Clustering Pipeline job submission process complete."
