#!/bin/bash

# This script generates and submits a SLURM job for the Neural Network pipelines
# (sequential classification and regression) using Keras Tuner.
# Outputs are organized into unique, job-specific directories.
# Personal information (First Name, Last Name, Email) is sourced from an external 'email.conf' file.

# --- Configuration for this SLURM Submission Script ---

# 1. Define the name for the temporary SLURM script file
TMP_SLURM_SCRIPT_NAME="my_nn_keras_tuner_job_submit.slurm"

# 2. Define shell variables for SLURM resource requests
REQUESTED_MEM="32G"
REQUESTED_CPUS="8"    # Total CPUs allocated by SLURM to this job. Keras/TensorFlow can use these.
REQUESTED_TIME="08:00:00"
JOB_NAME_BASE="NN_Pipeline_KT"

# --- Personal Information and Email Configuration ---
# These will be sourced from 'email.conf'
YOUR_EMAIL=""
SUBMISSION_FIRST_NAME=""
SUBMISSION_LAST_NAME=""

# 3. Source personal information from email.conf
# The email.conf file should contain lines like:
# YOUR_EMAIL="your.email@example.com"
# SUBMISSION_FIRST_NAME="YourFirstName"
# SUBMISSION_LAST_NAME="YourLastName"
CONF_FILE="email.conf"
echo "Looking for personal information configuration in: $(pwd)/${CONF_FILE}"
if [[ -f "$CONF_FILE" ]]; then
    source "$CONF_FILE" # Source the file to load the variables
    echo "Sourced personal info from $CONF_FILE:"
    if [[ -n "$YOUR_EMAIL" ]]; then
        echo "  Email: $YOUR_EMAIL"
    else
        echo "  Warning: YOUR_EMAIL not set or empty in $CONF_FILE. Email notifications may be affected."
        YOUR_EMAIL="" # Ensure it's empty if not properly set
    fi
    if [[ -n "$SUBMISSION_FIRST_NAME" ]]; then
        echo "  First Name: $SUBMISSION_FIRST_NAME"
    else
        echo "  Warning: SUBMISSION_FIRST_NAME not set or empty in $CONF_FILE. Output file naming will be affected."
        SUBMISSION_FIRST_NAME="FirstNameMissing" # Default placeholder
    fi
    if [[ -n "$SUBMISSION_LAST_NAME" ]]; then
        echo "  Last Name: $SUBMISSION_LAST_NAME"
    else
        echo "  Warning: SUBMISSION_LAST_NAME not set or empty in $CONF_FILE. Output file naming will be affected."
        SUBMISSION_LAST_NAME="LastNameMissing" # Default placeholder
    fi
else
    echo "Warning: Configuration file '$CONF_FILE' not found in $(pwd)."
    echo "  Email notifications will likely be disabled, and output file naming will use placeholders."
    YOUR_EMAIL=""
    SUBMISSION_FIRST_NAME="FirstNameNotFound"
    SUBMISSION_LAST_NAME="LastNameNotFound"
fi

# 4. Define the absolute path to your project's root directory
PROJECT_ROOT="/groups/kemi/kqd720/AppML/AppliedML2025/InitialProject" # MODIFY AS NEEDED

# 5. Define the name of your Python NN pipeline script
PYTHON_NN_PIPELINE_SCRIPT="run_nn_keras_tuner_v1.py"

# --- Submission Naming Parameters (Solution Names are set here) ---
# First Name and Last Name are sourced from email.conf
# MODIFY these solution names as needed for different runs/models
SUBMISSION_CLS_SOLUTION_NAME="KerasNN_Cls_Run1"
SUBMISSION_REG_SOLUTION_NAME="KerasNN_Reg_Run1"

# 6. Define parameters to be passed to the Python NN script
PYTHON_TRAIN_PATH_NN="./data/AppML_InitialProject_train.h5"
PYTHON_RANDOM_SEED_NN=42

# Classification specific arguments
PYTHON_CLS_TEST_PATH_NN="./data/AppML_InitialProject_test_classification.h5"
PYTHON_CLS_MAX_FEATURES_NN=25
PYTHON_CLS_KT_MAX_TRIALS_NN=10
PYTHON_CLS_KT_EPOCHS_NN=50
PYTHON_CLS_SELECTED_FEATURES_NN=""

# Regression specific arguments
PYTHON_REG_TEST_PATH_NN="./data/AppML_InitialProject_test_regression.h5"
PYTHON_REG_MAX_FEATURES_NN=12
PYTHON_REG_KT_MAX_TRIALS_NN=10
PYTHON_REG_KT_EPOCHS_NN=60
PYTHON_REG_SELECTED_FEATURES_NN=""

# Common arguments for the Python script
PYTHON_FINAL_MODEL_EPOCHS_NN=100

# Python script toggles
PYTHON_SKIP_CLS_TUNING_FLAG="" # Set to "--skip_cls_tuning" to skip
PYTHON_SKIP_REG_TUNING_FLAG="" # Set to "--skip_reg_tuning" to skip
PYTHON_DISABLE_CLS_FS_FLAG=""  # Set to "--disable_cls_feature_selection"
PYTHON_DISABLE_REG_FS_FLAG=""  # Set to "--disable_reg_feature_selection"


# --- Create the SLURM script content using a "here document" ---
echo "Generating SLURM script content for NN Keras Tuner Pipelines in $TMP_SLURM_SCRIPT_NAME..."
cat > "$TMP_SLURM_SCRIPT_NAME" <<EOF
#!/bin/bash
# SLURM script generated by: $0 on \$(date) for NN Keras Tuner Pipelines task

#----------------------------------------------------------------#
# SLURM Directives                                               #
#----------------------------------------------------------------#
#SBATCH --job-name=${JOB_NAME_BASE}_Cls_${SUBMISSION_CLS_SOLUTION_NAME}_Reg_${SUBMISSION_REG_SOLUTION_NAME}_%j # Use %j for SLURM Job ID
#SBATCH --account=chemistry
# CORRECTED: Use %j for job ID in path. SLURM will create job_runs_nn_kt/job_%j/
#SBATCH --output=${PROJECT_ROOT}/job_runs_nn_kt/job_%j/slurm_nn_kt-%j.out
#SBATCH --error=${PROJECT_ROOT}/job_runs_nn_kt/job_%j/slurm_nn_kt-%j.err
#SBATCH --partition=kemi6
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=${REQUESTED_CPUS}
#SBATCH --mem=${REQUESTED_MEM}
#SBATCH --time=${REQUESTED_TIME}
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=${YOUR_EMAIL} # Sourced by generator script

#----------------------------------------------------------------#
# Environment Setup and Script Execution                         #
#----------------------------------------------------------------#
echo "--------------------------------------------------------"
echo "SLURM Job ID: \$SLURM_JOB_ID" # This env var is set by SLURM
echo "SLURM CPUs per task: \$SLURM_CPUS_PER_TASK"
echo "Project Root Directory: ${PROJECT_ROOT}"
echo "Python script to run: ${PYTHON_NN_PIPELINE_SCRIPT}"
echo "Submission First Name: ${SUBMISSION_FIRST_NAME}"
echo "Submission Last Name: ${SUBMISSION_LAST_NAME}"
echo "Submission CLS Solution Name: ${SUBMISSION_CLS_SOLUTION_NAME}"
echo "Submission REG Solution Name: ${SUBMISSION_REG_SOLUTION_NAME}"
echo "Hostname: \$(hostname)"
echo "Working directory: \$(pwd)"
echo "Starting time: \$(date)"
echo "--------------------------------------------------------"

echo "Changing working directory to PROJECT_ROOT: ${PROJECT_ROOT}"
cd "${PROJECT_ROOT}"
if [ \$? -ne 0 ]; then echo "ERROR: cd to PROJECT_ROOT failed"; exit 1; fi
echo "Current Working Directory: \$(pwd)"

# Define the base directory for this job's outputs using the SLURM_JOB_ID environment variable
# This directory (job_runs_nn_kt/job_SLURM_JOB_ID) should be created by SLURM due to --output directive.
JOB_BASE_DIR_FOR_SLURM_JOB="${PROJECT_ROOT}/job_runs_nn_kt/job_\$SLURM_JOB_ID"
JOB_PYTHON_OUTPUT_DIR_NN="\${JOB_BASE_DIR_FOR_SLURM_JOB}/python_outputs_Cls_${SUBMISSION_CLS_SOLUTION_NAME}_Reg_${SUBMISSION_REG_SOLUTION_NAME}"

# Ensure the base directory for this job exists (SLURM should create it for --output, but -p helps ensure it)
# This step might be redundant if SLURM reliably creates the full path for --output, but it's safe.
mkdir -p "\$JOB_BASE_DIR_FOR_SLURM_JOB"
if [ \$? -ne 0 ]; then echo "ERROR: mkdir for job base directory failed: \$JOB_BASE_DIR_FOR_SLURM_JOB"; fi # Non-fatal if SLURM made it

# Then create the specific Python output subdirectory
mkdir -p "\$JOB_PYTHON_OUTPUT_DIR_NN"
if [ \$? -ne 0 ]; then echo "ERROR: mkdir for Python output directory failed: \$JOB_PYTHON_OUTPUT_DIR_NN"; exit 1; fi
echo "Python outputs will be in: \$JOB_PYTHON_OUTPUT_DIR_NN"

# 1. Initialize Micromamba
echo "--- Setting up Micromamba Environment ---"
export MAMBA_EXE='${MAMBA_EXE:-/lustre/hpc/kemi/kqd720/opt/x/micromamba}'
export MAMBA_ROOT_PREFIX='${MAMBA_ROOT_PREFIX:-/lustre/hpc/kemi/kqd720/micromamba}'
if [ ! -x "\$MAMBA_EXE" ]; then echo "ERROR: Micromamba not found at \$MAMBA_EXE"; exit 1; fi

__mamba_setup="\$("\$MAMBA_EXE" shell hook --shell bash --root-prefix "\$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ \$? -eq 0 ] && [ -n "\$__mamba_setup" ]; then
    eval "\$__mamba_setup";
else
    if [ -f "\$MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh" ]; then
        source "\$MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh"
    else
        echo "ERROR: Micromamba init failed." ; exit 1;
    fi
fi
unset __mamba_setup; echo "Micromamba hook initialized."

# 2. Activate Micromamba environment
ENV_NAME="${ENV_NAME:-AppML}"
echo "Activating Micromamba environment: \$ENV_NAME"
micromamba activate \$ENV_NAME
if [ \$? -ne 0 ]; then echo "ERROR: Failed to activate env '\$ENV_NAME'."; exit 1; fi
echo "Python: \$(which python), Version: \$(python --version)"
echo "TensorFlow version: \$(python -c 'import tensorflow as tf; print(tf.__version__)' 2>/dev/null || echo 'Not found')"
echo "Keras Tuner version: \$(python -c 'import keras_tuner as kt; print(kt.__version__)' 2>/dev/null || echo 'Not found')"
# ... other package version checks ...
echo "------------------------------------------"

# 3. Construct and Execute Python NN script command
PYTHON_SCRIPT_TO_RUN_NN="${PYTHON_NN_PIPELINE_SCRIPT}"

PYTHON_CMD="python -u ./\$PYTHON_SCRIPT_TO_RUN_NN"
PYTHON_CMD+=" --output_base_dir \"\$JOB_PYTHON_OUTPUT_DIR_NN\""
PYTHON_CMD+=" --firstname \"${SUBMISSION_FIRST_NAME}\""
PYTHON_CMD+=" --lastname \"${SUBMISSION_LAST_NAME}\""
PYTHON_CMD+=" --cls_solution_name \"${SUBMISSION_CLS_SOLUTION_NAME}\""
PYTHON_CMD+=" --reg_solution_name \"${SUBMISSION_REG_SOLUTION_NAME}\""
PYTHON_CMD+=" --train_path \"${PYTHON_TRAIN_PATH_NN}\""
PYTHON_CMD+=" --random_seed ${PYTHON_RANDOM_SEED_NN}"
PYTHON_CMD+=" --final_model_epochs ${PYTHON_FINAL_MODEL_EPOCHS_NN}"

# Classification arguments
PYTHON_CMD+=" --cls_test_path \"${PYTHON_CLS_TEST_PATH_NN}\""
PYTHON_CMD+=" --cls_max_features ${PYTHON_CLS_MAX_FEATURES_NN}"
PYTHON_CMD+=" --cls_kt_max_trials ${PYTHON_CLS_KT_MAX_TRIALS_NN}"
PYTHON_CMD+=" --cls_kt_epochs ${PYTHON_CLS_KT_EPOCHS_NN}"
if [ -n "${PYTHON_CLS_SELECTED_FEATURES_NN}" ]; then PYTHON_CMD+=" --cls_selected_features_list \"${PYTHON_CLS_SELECTED_FEATURES_NN}\""; fi
if [ -n "${PYTHON_SKIP_CLS_TUNING_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SKIP_CLS_TUNING_FLAG}"; fi
if [ -n "${PYTHON_DISABLE_CLS_FS_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_DISABLE_CLS_FS_FLAG}"; fi

# Regression arguments
PYTHON_CMD+=" --reg_test_path \"${PYTHON_REG_TEST_PATH_NN}\""
PYTHON_CMD+=" --reg_max_features ${PYTHON_REG_MAX_FEATURES_NN}"
PYTHON_CMD+=" --reg_kt_max_trials ${PYTHON_REG_KT_MAX_TRIALS_NN}"
PYTHON_CMD+=" --reg_kt_epochs ${PYTHON_REG_KT_EPOCHS_NN}"
if [ -n "${PYTHON_REG_SELECTED_FEATURES_NN}" ]; then PYTHON_CMD+=" --reg_selected_features_list \"${PYTHON_REG_SELECTED_FEATURES_NN}\""; fi
if [ -n "${PYTHON_SKIP_REG_TUNING_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SKIP_REG_TUNING_FLAG}"; fi
if [ -n "${PYTHON_DISABLE_REG_FS_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_DISABLE_REG_FS_FLAG}"; fi

echo ""
echo "--- Running Python NN Keras Tuner Pipeline Script ---"
printf "Executing Python Command:\n%s\n" "\$PYTHON_CMD"
echo "--------------------------------------------------------"
eval "\$PYTHON_CMD"

SCRIPT_EXIT_STATUS=\$?
if [ \$SCRIPT_EXIT_STATUS -eq 0 ]; then
    echo "Python script '\$PYTHON_SCRIPT_TO_RUN_NN' completed successfully."
    echo "Submission files should be in \$JOB_PYTHON_OUTPUT_DIR_NN"
else
    echo "ERROR: Python script '\$PYTHON_SCRIPT_TO_RUN_NN' exited with status \$SCRIPT_EXIT_STATUS."
fi
echo "--------------------------------------------------------"

# 4. Deactivate Micromamba environment
echo ""; echo "--- Cleaning Up ---"; echo "Deactivating Micromamba environment."
micromamba deactivate; echo "Micromamba environment deactivated."
echo "-------------------"

echo ""; echo "--------------------------------------------------------"
echo "Ending time: \$(date)"; echo "SLURM job finished."
echo "--------------------------------------------------------"
exit \$SCRIPT_EXIT_STATUS
EOF

if [ $? -eq 0 ]; then
    echo "Successfully wrote SLURM script content for NN Keras Tuner Pipelines to $TMP_SLURM_SCRIPT_NAME"
else
    echo "ERROR writing to $TMP_SLURM_SCRIPT_NAME"; exit 1;
fi

echo ""; echo "Submitting generated NN Keras Tuner SLURM script: $TMP_SLURM_SCRIPT_NAME to the queue..."

SBATCH_FULL_OUTPUT=$(sbatch "$TMP_SLURM_SCRIPT_NAME" 2>&1)
SBATCH_COMMAND_EXIT_CODE=$?

echo "Full output from sbatch command:"
echo "$SBATCH_FULL_OUTPUT"
echo "sbatch command finished with exit code: $SBATCH_COMMAND_EXIT_CODE"

SUBMITTED_JOB_ID=$(echo "$SBATCH_FULL_OUTPUT" | grep -oP 'Submitted batch job \K[0-9]+')

if [ -n "$SUBMITTED_JOB_ID" ]; then
    echo "Successfully submitted SLURM job. Job ID: $SUBMITTED_JOB_ID"
    if [ "$SBATCH_COMMAND_EXIT_CODE" -ne 0 ]; then
        echo "Warning: The sbatch command exited with a non-zero status ($SBATCH_COMMAND_EXIT_CODE), but a Job ID ($SUBMITTED_JOB_ID) was parsed."
    fi
elif [ "$SBATCH_COMMAND_EXIT_CODE" -eq 0 ]; then
    echo "Warning: sbatch command exited successfully, but no Job ID was parsed."
else
    echo "ERROR: SLURM job submission failed. Exit code \$SBATCH_COMMAND_EXIT_CODE."
fi

echo ""; echo "NN Keras Tuner Pipeline job submission process complete."

