#!/bin/bash

# This script generates and submits a SLURM job for the Neural Network pipelines
# (sequential classification and regression) using Keras Tuner.
# Outputs are organized into unique, job-specific directories.

# --- Configuration for this SLURM Submission Script ---

# 1. Define the name for the temporary SLURM script file
TMP_SLURM_SCRIPT_NAME="my_nn_keras_tuner_job_submit.slurm"

# 2. Define shell variables for SLURM resource requests
REQUESTED_MEM="32G"  
REQUESTED_CPUS="8"    # Total CPUs allocated by SLURM to this job. Keras/TensorFlow can use these.
REQUESTED_TIME="08:00:00" 
JOB_NAME_BASE="NN_Pipeline_KT" # Updated job name base for Keras Tuner
YOUR_EMAIL="" 

# 3. Source the email address for notifications
EMAIL_CONF_FILE="email.conf" 
echo "Looking for email configuration in: $(pwd)/${EMAIL_CONF_FILE}"
if [[ -f "$EMAIL_CONF_FILE" ]]; then
    source "$EMAIL_CONF_FILE"; echo "Sourced email: $YOUR_EMAIL"
    [[ -z "$YOUR_EMAIL" ]] && echo "Warning: YOUR_EMAIL empty in $EMAIL_CONF_FILE." && YOUR_EMAIL=""
else
    echo "Warning: $EMAIL_CONF_FILE not found. Email notifications likely disabled."
fi

# 4. Define the absolute path to your project's root directory
PROJECT_ROOT="/groups/kemi/kqd720/AppML/AppliedML2025/InitialProject" # MODIFY AS NEEDED

# 5. Define the name of your Python NN pipeline script (the refactored one)
PYTHON_NN_PIPELINE_SCRIPT="run_nn_keras_tuner_v1.py" # Make sure this matches your Python script filename

# 6. Define parameters to be passed to the Python NN script
PYTHON_TRAIN_PATH_NN="./data/AppML_InitialProject_train.h5"
PYTHON_RANDOM_SEED_NN=42

# Classification specific arguments (for Keras Tuner)
PYTHON_CLS_TEST_PATH_NN="./data/AppML_InitialProject_test_classification.h5"
PYTHON_CLS_MAX_FEATURES_NN=25
PYTHON_CLS_KT_MAX_TRIALS_NN=10 # Keras Tuner max trials
PYTHON_CLS_KT_EPOCHS_NN=50     # Keras Tuner epochs per trial
PYTHON_CLS_SELECTED_FEATURES_NN="" # Example: "feature1,feature2,feature3" or empty for placeholder

# Regression specific arguments (for Keras Tuner)
PYTHON_REG_TEST_PATH_NN="./data/AppML_InitialProject_test_regression.h5"
PYTHON_REG_MAX_FEATURES_NN=12
PYTHON_REG_KT_MAX_TRIALS_NN=10 # Keras Tuner max trials
PYTHON_REG_KT_EPOCHS_NN=60     # Keras Tuner epochs per trial
PYTHON_REG_SELECTED_FEATURES_NN="" # Example: "featureA,featureB" or empty for placeholder

# Common arguments for the Python script
PYTHON_FINAL_MODEL_EPOCHS_NN=100 # Epochs for training the final model after tuning

# Python script toggles for skipping tuning
PYTHON_SKIP_CLS_TUNING_FLAG="" # Set to "--skip_cls_tuning" to skip
PYTHON_SKIP_REG_TUNING_FLAG="" # Set to "--skip_reg_tuning" to skip


# --- Create the SLURM script content using a "here document" ---
echo "Generating SLURM script content for NN Keras Tuner Pipelines in $TMP_SLURM_SCRIPT_NAME..."
cat > "$TMP_SLURM_SCRIPT_NAME" <<EOF
#!/bin/bash
# SLURM script generated by: $0 on $(date) for NN Keras Tuner Pipelines task

#----------------------------------------------------------------#
# SLURM Directives                                               #
#----------------------------------------------------------------#
#SBATCH --job-name=${JOB_NAME_BASE}_%j
#SBATCH --account=chemistry # MODIFY if needed
#SBATCH --output=${PROJECT_ROOT}/job_runs_nn_kt/job_%j/slurm_nn_kt-%j.out # Updated output path
#SBATCH --error=${PROJECT_ROOT}/job_runs_nn_kt/job_%j/slurm_nn_kt-%j.err  # Updated error path
#SBATCH --partition=kemi6 # MODIFY if needed
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=${REQUESTED_CPUS} # This is \$SLURM_CPUS_PER_TASK for the job
#SBATCH --mem=${REQUESTED_MEM}
#SBATCH --time=${REQUESTED_TIME}
#SBATCH --mail-type=FAIL,END 
#SBATCH --mail-user=${YOUR_EMAIL}

#----------------------------------------------------------------#
# Environment Setup and Script Execution                         #
#----------------------------------------------------------------#
echo "--------------------------------------------------------"
echo "SLURM Job ID: \$SLURM_JOB_ID" 
echo "SLURM CPUs per task (Total allocated to this job): \$SLURM_CPUS_PER_TASK"
echo "Project Root Directory: ${PROJECT_ROOT}"
echo "Python script to run: ${PYTHON_NN_PIPELINE_SCRIPT}"
echo "Hostname: \$(hostname)"
echo "Working directory: \$(pwd)"
echo "Starting time: \$(date)" 
echo "--------------------------------------------------------"

echo "Changing working directory to PROJECT_ROOT: ${PROJECT_ROOT}"
cd "${PROJECT_ROOT}"
if [ \$? -ne 0 ]; then echo "ERROR: cd to PROJECT_ROOT failed"; exit 1; fi
echo "Current Working Directory: \$(pwd)" 

# Create a job-specific directory for Python outputs
JOB_PYTHON_OUTPUT_DIR_NN="${PROJECT_ROOT}/job_runs_nn_kt/job_\$SLURM_JOB_ID/python_nn_kt_outputs_\$(date +%Y%m%d-%H%M%S)" 
mkdir -p "\$JOB_PYTHON_OUTPUT_DIR_NN" 
if [ \$? -ne 0 ]; then echo "ERROR: mkdir for Python output directory failed"; exit 1; fi
echo "Python outputs will be in: \$JOB_PYTHON_OUTPUT_DIR_NN"

# 1. Initialize Micromamba
echo "--- Setting up Micromamba Environment ---"
export MAMBA_EXE='/lustre/hpc/kemi/kqd720/opt/x/micromamba'; export MAMBA_ROOT_PREFIX='/lustre/hpc/kemi/kqd720/micromamba' # MODIFY AS NEEDED
if [ ! -x "\$MAMBA_EXE" ]; then echo "ERROR: Micromamba not found at \$MAMBA_EXE"; exit 1; fi

__mamba_setup="\$("\$MAMBA_EXE" shell hook --shell bash --root-prefix "\$MAMBA_ROOT_PREFIX" 2> /dev/null)" 
if [ \$? -eq 0 ] && [ -n "\$__mamba_setup" ]; then 
    eval "\$__mamba_setup"; 
else 
    echo "ERROR: Micromamba hook failed. Attempting to source profile.d script if it exists..."
    if [ -f "\$MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh" ]; then
        source "\$MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh"
    else
        echo "ERROR: Micromamba hook and profile.d script failed. Cannot initialize Micromamba."
        exit 1;
    fi
fi
unset __mamba_setup; echo "Micromamba hook initialized."

# 2. Activate Micromamba environment
ENV_NAME="AppML" # MODIFY if your environment name is different
echo "Activating Micromamba environment: \$ENV_NAME" 
micromamba activate \$ENV_NAME 
if [ \$? -ne 0 ]; then echo "ERROR: Failed to activate env '\$ENV_NAME'. Ensure it exists and Keras Tuner is installed."; exit 1; fi
echo "Micromamba environment activated. Python: \$(which python)" 
echo "Python version: \$(python --version)"
echo "TensorFlow version: \$(python -c 'import tensorflow as tf; print(tf.__version__)')"
echo "Keras Tuner version: \$(python -c 'import keras_tuner as kt; print(kt.__version__)')"
echo "Scikit-learn version: \$(python -c 'import sklearn; print(sklearn.__version__)')"
echo "SciKeras version: \$(python -c 'import scikeras; print(scikeras.__version__)')"
echo "------------------------------------------"

# 3. Construct and Execute Python NN script command
PYTHON_SCRIPT_TO_RUN_NN="${PYTHON_NN_PIPELINE_SCRIPT}" 

PYTHON_CMD="python -u ./\$PYTHON_SCRIPT_TO_RUN_NN"
PYTHON_CMD+=" --output_base_dir \"\$JOB_PYTHON_OUTPUT_DIR_NN\""
PYTHON_CMD+=" --train_path \"${PYTHON_TRAIN_PATH_NN}\""
PYTHON_CMD+=" --random_seed ${PYTHON_RANDOM_SEED_NN}"
PYTHON_CMD+=" --final_model_epochs ${PYTHON_FINAL_MODEL_EPOCHS_NN}"

# Classification arguments
PYTHON_CMD+=" --cls_test_path \"${PYTHON_CLS_TEST_PATH_NN}\""
PYTHON_CMD+=" --cls_max_features ${PYTHON_CLS_MAX_FEATURES_NN}"
PYTHON_CMD+=" --cls_kt_max_trials ${PYTHON_CLS_KT_MAX_TRIALS_NN}"
PYTHON_CMD+=" --cls_kt_epochs ${PYTHON_CLS_KT_EPOCHS_NN}"
if [ -n "${PYTHON_CLS_SELECTED_FEATURES_NN}" ]; then PYTHON_CMD+=" --cls_selected_features_list \"${PYTHON_CLS_SELECTED_FEATURES_NN}\""; fi
if [ -n "${PYTHON_SKIP_CLS_TUNING_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SKIP_CLS_TUNING_FLAG}"; fi

# Regression arguments
PYTHON_CMD+=" --reg_test_path \"${PYTHON_REG_TEST_PATH_NN}\""
PYTHON_CMD+=" --reg_max_features ${PYTHON_REG_MAX_FEATURES_NN}"
PYTHON_CMD+=" --reg_kt_max_trials ${PYTHON_REG_KT_MAX_TRIALS_NN}"
PYTHON_CMD+=" --reg_kt_epochs ${PYTHON_REG_KT_EPOCHS_NN}"
if [ -n "${PYTHON_REG_SELECTED_FEATURES_NN}" ]; then PYTHON_CMD+=" --reg_selected_features_list \"${PYTHON_REG_SELECTED_FEATURES_NN}\""; fi
if [ -n "${PYTHON_SKIP_REG_TUNING_FLAG}" ]; then PYTHON_CMD+=" ${PYTHON_SKIP_REG_TUNING_FLAG}"; fi


echo ""
echo "--- Running Python NN Keras Tuner Pipeline Script ---"
printf "Executing Python Command:\n%s\n" "\$PYTHON_CMD" 
echo "--------------------------------------------------------"
eval "\$PYTHON_CMD"

SCRIPT_EXIT_STATUS=\$? 
if [ \$SCRIPT_EXIT_STATUS -eq 0 ]; then 
    echo "Python script '\$PYTHON_SCRIPT_TO_RUN_NN' completed successfully." 
else 
    echo "ERROR: Python script '\$PYTHON_SCRIPT_TO_RUN_NN' exited with status \$SCRIPT_EXIT_STATUS."
fi
echo "--------------------------------------------------------"

# 4. Deactivate Micromamba environment
echo ""; echo "--- Cleaning Up ---"; echo "Deactivating Micromamba environment."
micromamba deactivate; echo "Micromamba environment deactivated."
echo "-------------------"

echo ""; echo "--------------------------------------------------------"
echo "Ending time: \$(date)"; echo "SLURM job finished."
echo "--------------------------------------------------------"
exit \$SCRIPT_EXIT_STATUS 
EOF

if [ $? -eq 0 ]; then 
    echo "Successfully wrote SLURM script content for NN Keras Tuner Pipelines to $TMP_SLURM_SCRIPT_NAME"
else 
    echo "ERROR writing to $TMP_SLURM_SCRIPT_NAME"; exit 1; 
fi

echo ""; echo "Submitting generated NN Keras Tuner SLURM script: $TMP_SLURM_SCRIPT_NAME to the queue..."

# MODIFIED SECTION for sbatch handling:
# Capture stdout and stderr of sbatch to check its output and exit code robustly
SBATCH_FULL_OUTPUT=$(sbatch "$TMP_SLURM_SCRIPT_NAME" 2>&1)
SBATCH_COMMAND_EXIT_CODE=$?

# Log the full output from the sbatch command for debugging
echo "Full output from sbatch command:"
echo "$SBATCH_FULL_OUTPUT"
echo "sbatch command finished with exit code: $SBATCH_COMMAND_EXIT_CODE"

# Try to parse the Job ID from the sbatch output
# This regex looks for "Submitted batch job" followed by digits.
SUBMITTED_JOB_ID=$(echo "$SBATCH_FULL_OUTPUT" | grep -oP 'Submitted batch job \K[0-9]+')

if [ -n "$SUBMITTED_JOB_ID" ]; then
    # A Job ID was found in the output
    echo "Successfully submitted SLURM job. Job ID: $SUBMITTED_JOB_ID"
    if [ "$SBATCH_COMMAND_EXIT_CODE" -ne 0 ]; then
        # sbatch exited non-zero, but we got a Job ID (e.g., sbatch might have issued a warning)
        echo "Warning: The sbatch command exited with a non-zero status ($SBATCH_COMMAND_EXIT_CODE), but a Job ID ($SUBMITTED_JOB_ID) was parsed."
        echo "The job may have been submitted despite the warning. Please verify its status in the SLURM queue."
    fi
elif [ "$SBATCH_COMMAND_EXIT_CODE" -eq 0 ]; then
    # sbatch exited with 0, but we couldn't find a Job ID in its output. This is unusual.
    echo "Warning: sbatch command exited successfully (code 0), but no Job ID could be parsed from its output."
    echo "Please check the SLURM queue manually to see if the job was submitted."
else
    # sbatch exited non-zero, AND no Job ID was found. Submission likely failed.
    echo "ERROR: SLURM job submission failed. sbatch command exited with status $SBATCH_COMMAND_EXIT_CODE and no Job ID was parsed."
fi
# END OF MODIFIED SECTION

echo ""; echo "NN Keras Tuner Pipeline job submission process complete."
